# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HOSTAPP' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HOSTAPP
  
  # Development Pod
  #pod 'FRAMEWORK', :path => '../FRAMEWORK'
  
  # "Git" Pod
  pod 'FRAMEWORK', :git => '../FRAMEWORK'
  
end
